export {
  addAdditional,
  addToCart,
  changeAdditionalQuantity,
  clearCart,
  decreaseQuantity,
  increaseQuantity,
  removeFromCart,
  setAdditionals,
  setCustomerAddress,
  setCustomerAddressError,
  setCustomerEmail,
  setCustomerEmailError,
  setCustomerName,
  setCustomerNameError,
  setCustomerNote,
  setCustomerPhone,
  setCustomerPhoneError,
  setCutleryAmount,
  setDeliveryPrice,
  setPickup,
  setAgree,
  setAgreeError,
  setSchedule,
  setShopSettings,
  setTotalRollsDiscount,
} from "./actions";
export { useStore, AppContext } from "./context";
export { reducer } from "./reducer";
export type {
  TCartProduct,
  TAdditional,
  TSchedule,
  TShopSettings,
} from "./initialState";
