query CartPageQuery {
  additionals {
    id
    title
    price
  }

  hero_cs: hero(locale: "cs") {
    image {
      url
    }
    locale
    text
    title
  }

  hero_ru: hero(locale: "ru") {
    image {
      url
    }
    locale
    text
    title
  }

  products(sort: "created_at") {
    allergeny
    id
    image {
      url
    }
    ingredients
    isRoll
    persons
    price
    slug
    title
    weight
  }

  cutlery {
    price
  }

  shop {
    shopIsClosed
  }

  schedule_cs: schedule(locale: "cs") {
    locale
    schedule
    text
    title
  }

  schedule_ru: schedule(locale: "ru") {
    locale
    schedule
    text
    title
  }
}
