query HomePageQuery {
  additionals {
    id
    title
    price
  }

  about_cs: about(locale: "cs") {
    locale
    text
    title
  }

  about_ru: about(locale: "ru") {
    locale
    text
    title
  }

  banner_cs: banner(locale: "cs") {
    image {
      url
    }
    locale
  }

  banner_ru: banner(locale: "ru") {
    image {
      url
    }
    locale
  }

  deliveryTitle_cs: deliveryTitle(locale: "cs") {
    locale
    title
  }

  deliveryTitle_ru: deliveryTitle(locale: "ru") {
    locale
    title
  }

  deliveryItems(locale: "all") {
    locale
    text
    title
  }

  hero_cs: hero(locale: "cs") {
    image {
      url
    }
    locale
    text
    title
  }

  hero_ru: hero(locale: "ru") {
    image {
      url
    }
    locale
    text
    title
  }

  products(sort: "created_at") {
    allergeny
    id
    image {
      url
    }
    ingredients
    isRoll
    isSalat
    isDrink
    price
    slug
    title
    weight
  }

  reviews {
    image {
      url
    }
  }

  schedule_cs: schedule(locale: "cs") {
    locale
    schedule
    text
    title
  }

  schedule_ru: schedule(locale: "ru") {
    locale
    schedule
    text
    title
  }

  shop {
    shopIsClosed
  }
}
