query ProductPageQuery {
  days(where: { active: true }) {
    day
    schedule
    title
  }

  hero_cs: hero(locale: "cs") {
    image {
      url
    }
    locale
    text
    title
  }

  hero_ru: hero(locale: "ru") {
    image {
      url
    }
    locale
    text
    title
  }

  products(sort: "priority") {
    allergeny
    id
    image {
      url
    }
    ingredients
    isRoll
    isSalat
    isDrink
    isPoke
    isSet
    price
    slug
    title
    weight
  }

  shop {
    ordersStop
    shopIsClosed
  }
}
