query TermsPageQuery {
  days(where: { active: true }) {
    day
    schedule
    title
  }

  hero_cs: hero(locale: "cs") {
    image {
      url
    }
    locale
    text
    title
  }

  hero_ru: hero(locale: "ru") {
    image {
      url
    }
    locale
    text
    title
  }
}
