export { About } from "./About";
export { Banner } from "./Banner";
export { Cart } from "./Cart";
export { Contacts } from "./Contacts";
export { Delivery } from "./Delivery";
export { Layout, LayoutSecondary } from "./Layout";
export { Media } from "./Media";
export { Modal } from "./Modal";
export { ProductDetails } from "./ProductDetails";
export { Products } from "./Products";
export { ProductsRecommended } from "./ProductsRecommended";
export { Reviews } from "./Reviews";
export { ShopModal } from "./ShopModal";

export type { TAbout } from "./About/types";
export type { TBanner } from "./Banner/types";
export type { TDelivery } from "./Delivery/types";
export type { TMedia } from "./Media";
export type { TReview } from "./Reviews";
export type { TProduct, TProductModifier } from "./ProductDetails/types";
