export { About } from "./About";
export { Banner } from "./Banner";
export { Cart } from "./Cart";
export { Contacts } from "./Contacts";
export { Delivery } from "./Delivery";
export { Layout } from "./Layout";
export { Modal } from "./Modal";
export { Products } from "./Products";
export { Reviews } from "./Reviews";
