export const LangStrings = {
  cs: {
    metaDescription: `Každý set je tvořen s láskou, z čerstvých ingrediencí a ve správné kombinaci. Na doručení používáme 
      EKO boxy, abychom aspoň trochu odlehčili přírodě.`,
    mainTitle: "Sushi Man | Rozvoz sushi po Praze",
    cartTitle: "Sushi Man | Košik",
    mainMenu: [
      {
        anchor: "about-section",
        text: "O nas",
      },
      {
        anchor: "products-section",
        text: "Menu",
      },
      {
        anchor: "delivery-section",
        text: "Doprava a platba",
      },
      {
        anchor: "reviews-section",
        text: "Recenze",
      },
      {
        anchor: "footer",
        text: "Kontakty",
      },
    ],
    innerMenu: [
      {
        anchor: "/",
        text: "Hlavni",
      },
      {
        anchor: "/#products-section",
        text: "Menu",
      },
      {
        anchor: "/#delivery-section",
        text: "Doprava a platba",
      },
      {
        anchor: "/#reviews-section",
        text: "Recenze",
      },
      {
        anchor: "/#footer",
        text: "Kontakty",
      },
    ],
    phoneNumber: "+420 792 745 116",
    langs: ["cz", "ru"],
    welcomeTitle: "Rozvoz sushi po Praze<br />Vyrobeno s láskou!",
    welcomeSubTitle:
      "Při každou 5 objednávce, roll “tempura maki” <br />nebo “obyčejné maki”, dle výběru - ZDARMA",
    welcomeButton: "Menu",
    contactsLinks: [
      {
        url: "https://instagram.com/sushiman_prague",
        type: "instagram",
      },
      {
        url: "http://t.me/sushimanprague",
        type: "telegram",
      },
      {
        url: "https://wa.me/420792745116?text=Здравствуйте.%20Хочу%20сделать%20заказ!",
        type: "whatsapp",
      },
      {
        url: "viber://chat?number=%2B420792745116#",
        type: "viber",
      },
      {
        url: "tel:+420792745116",
        type: "phone",
      },
    ],
    productsTitle: "Menu",
    reviewsTitle: "Recenze",
    reviewsImages: [
      "reviews_img.png",
      "reviews_img2.png",
      "reviews_img3.png",
      "reviews_img4.png",
      "reviews_img5.png",
      "reviews_img6.png",
      "reviews_img7.png",
      "reviews_img8.png",
      "reviews_img9.png",
      "reviews_img10.png",
      "reviews_img11.png",
      "reviews_img12.png",
      "reviews_img13.png",
      "reviews_img14.png",
      "reviews_img15.png",
      "reviews_img16.png",
      "reviews_img17.png",
      "reviews_img18.png",
      "reviews_img19.png",
      "reviews_img20.png",
      "reviews_img21.png",
      "reviews_img22.png",
      "reviews_img23.png",
      "reviews_img24.png",
    ],
    reviewsButton: "Objednat",
    modalTitle: "Rozvážíme<br />",
    modalText: "Pn. - Ut. - Zavřeno<br />St. - Ne. 11:00 - 22:00",
    shopModalTitle: "Dneska máme zavřeno<br />",
    ordersStopModalTitle: "Teď objednat není možné",
    ordersStopModalText: `Vážený přátele, dneska jsme dosáhli maximálního počtu objednávek ve frontě, proto prosím Vás zkusit objednat později.`,
    allergeny: "Seznam alergenů",
    allergenyImage: "allergeny_cz_img.jpg",
    mediaImage: "discount_img.jpg",
    recommendedTitle: "Chcete ještě něco přidat?",
    addToCart: "Přidat do košíku",
    quantity: "Množství / Váha",
    price: "Cena",
    priceTotal: "Konečná cena",
    goToPay: "Pokračovat k platbě",
    modifiers: "Modifikátory",
    ingredients: "Složení",
    cartIsEmpty: "Košík je prázdný",
    payByCash: "Platba v hotovosti",
    payByCard: "Platba kartou on-line",
    payByCardPickup: "Platba kartou na místě",
    payByCardCourier: "Platba kartou kuriru",
    paymentMethods: "Způsoby platby",
    addMore: "Přidat navíc",
    priceIncluded:
      "Pozor na to, že rolly a sety už mají v ceně Vasabi, Zázvor a Sójovku!",
    deliveryLabel: "Doručení kurýrem",
    pickupLabel: "Vyzvednout",
    deliveryPrice: "Cena doručení",
    cutleryQuantity: "Pro kolik lidi přidat příbory",
    cutleryPriceIncluded: "příborů můžete přidat zdarma.",
    addMoreRolls: "Přidejte ještě",
    addMoreRollsResult: "rolly a získejte",
    remove: "Odstranit",
    delivery: "Doručení",
    order: "Objednávka",
    discountReceived: "Dostal(a) jste Slevu",
    name: "Jméno",
    email: "E-mail",
    phone: "Telefon (420 123 456 789)",
    address: "Adresa",
    fillAddress: "Adresa",
    pickupAddress: "Adresa pro vyzvednutí",
    personsDescription: "Hůlky, ubrousky a misky na sójovku.",
    promoTitle: "Promo code",
  },
  ru: {
    metaDescription: `По-настоящему вкусные и сочные сеты, которые Вас вдоволь накормят и насладят 
      сбалансированным вкусом всех ингредиентов! Готовим с душой и любовью для Вас.`,
    mainTitle: "Sushi Man | Доставка суши по Праге",
    cartTitle: "Sushi Man | Корзина",
    mainMenu: [
      {
        anchor: "about-section",
        text: "О нас",
      },
      {
        anchor: "products-section",
        text: "Меню",
      },
      {
        anchor: "delivery-section",
        text: "Доставка и оплата",
      },
      {
        anchor: "reviews-section",
        text: "Отзывы",
      },
    ],
    innerMenu: [
      {
        anchor: "/",
        text: "Главная",
      },
    ],
    phoneNumber: "+420 792 745 116",
    langs: ["cz", "ru"],
    welcomeTitle: "Доставка суши по Праге<br />Сделано c душой!",
    welcomeSubTitle:
      "При каждом пятом заказе сета, ролл “tempura maki” <br />или “обычный maki”, на Ваш выбор - БЕСПЛАТНО",
    welcomeButton: "Меню",
    contactsLinks: [
      {
        url: "https://instagram.com/sushiman_prague",
        type: "instagram",
      },
      {
        url: "http://t.me/sushimanprague",
        type: "telegram",
      },
      {
        url: "https://wa.me/420792745116?text=Здравствуйте.%20Хочу%20сделать%20заказ!",
        type: "whatsapp",
      },
      {
        url: "viber://chat?number=%2B420792745116#",
        type: "viber",
      },
      {
        url: "tel:+420792745116",
        type: "phone",
      },
    ],
    productsTitle: "Меню",
    reviewsTitle: "Отзывы",
    reviewsImages: [
      "reviews_img.png",
      "reviews_img2.png",
      "reviews_img3.png",
      "reviews_img4.png",
      "reviews_img5.png",
      "reviews_img6.png",
      "reviews_img7.png",
      "reviews_img8.png",
      "reviews_img9.png",
      "reviews_img10.png",
      "reviews_img11.png",
      "reviews_img12.png",
      "reviews_img13.png",
      "reviews_img14.png",
      "reviews_img15.png",
      "reviews_img16.png",
      "reviews_img17.png",
      "reviews_img18.png",
      "reviews_img19.png",
      "reviews_img20.png",
      "reviews_img21.png",
      "reviews_img22.png",
      "reviews_img23.png",
      "reviews_img24.png",
    ],
    reviewsButton: "Заказать",
    modalTitle: "Доставляем<br />",
    shopModalTitle: "",
    ordersStopModalTitle: "",
    ordersStopModalText: ``,
    modalText: "od 11:00 do 21:00",
    allergeny: "Список аллергенов",
    allergenyImage: "allergeny_ru_img.jpg",
    mediaImage: "discount_img2.jpg",
    recommendedTitle: "Хотите ещё что-то добавить?",
    addToCart: "Добавить в корзину",
    quantity: "Количество / Вес",
    price: "Цена",
    priceTotal: "Итоговая цена",
    modifiers: "Модификаторы",
    ingredients: "Состав",
    personsDescription: "Hůlky, ubrousky a misky na sójovku.",
  },
};
